### ISSUE TITLE
转换问题

### ISSUE THREAD

**Issue by a7502** [Mikachu2333/BiliAuDown#1]
m4a转MP3后的文件在那呢？找不到啊，转flac也找不到在那，

**Comment by Mikachu2333** [comment]
就在程序的目录下，如果没有的话请检查是否在本目录下存在ffmpeg

程序转换3步走：
1.下载（m4a格式）
2.点击按钮以后（m4a格式与mp3或flac并存）
3.结束后（仅存转换后的格式，m4a被自动删除）

如果没有ffmpeg，则下载的音乐会被自动删除，表现为m4a格式的文件也没了

**Comment by a7502** [comment]
有ffmpeg，转换好像没不行。

玖兰百夜烟花 ***@***.***> 于2023年7月30日周日 21:26写道：

**Comment by a7502** [comment]
有ffmpeg，转换好像不行。

jk jk ***@***.***> 于2023年7月31日周一 18:21写道：

**Comment by a7502** [comment]
***@***.***

jk jk ***@***.***> 于2023年7月31日周一 18:24写道：

**Comment by a7502** [comment]
我重新下载ffmpeg好像是可以了

**Comment by Mikachu2333** [comment]
okok
